function Hd = highPass3200
%HIGHPASS3200 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 14-Aug-2019 13:45:00

% Elliptic Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 7000;  % Sampling Frequency

N     = 6;     % Order
Fpass = 3200;  % Passband Frequency
Apass = 3;     % Passband Ripple (dB)
Astop = 40;    % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.highpass('N,Fp,Ast,Ap', N, Fpass, Astop, Apass, Fs);
Hd = design(h, 'ellip');

% [EOF]
